#pragma once

#define SCREEN_WIDTH 978
#define SCREEN_HEIGHT 600

#define SCREEN_WCENTER SCREEN_WIDTH / 2;
#define SCREEN_HCENTER SCREEN_HEIGHT / 2;

LRESULT CALLBACK WindowProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam);